### ISSUE TITLE
pkg-config file points to a Qt4 libs when build kqoauth with Qt5

### ISSUE THREAD

**Issue by sl1pkn07** [kypeli/kQOAuth#12]
when build kqoauth with Qt5, the .pc file points to Qt4 libs instead of a Qt5 libs

```
Requires: QtCore QtNetwork
```

instead of:

```
Requires: Qt5Core Qt5Network
```

https://github.com/kypeli/kQOAuth/blob/master/src/pcfile.sh#L13
greetings

**Comment by kypeli** [comment]
Thank you for the message! Unfortunately I haven't updated kQOAuth in
years, nor am I interested in Qt anymore. Thus, at the time when it was
developed, Qt4 was the latest version.

I have no plans maintaining or updating kQOAuth anymore. Feel free to
submit a pull request to fix the issue, and I am happy to merge it.

Cheers,

Johan
