### ISSUE TITLE
Libdir at ppc64

### ISSUE THREAD

**Issue by DAP-DarkneSS** [kypeli/kQOAuth#3]
Hello. In the x64 openSUSE libs are situated at prefix/usr/lib64
The build at x86_64 succeeds, but at ppc64 libs are put to prefix/usr/lib

**Comment by kypeli** [comment]
Thanks for the report! I don't have openSUSE nor ppc64 so I can make the change, but I have no way of verifying if it actually works.

Hence I would appreciate a contribution / merge request from someone who can actually implement and test this.

**Comment by DAP-DarkneSS** [comment]
I could only test to build. I don't have a ppc64 machine, so there are no possibility to test the result built.

**Comment by DAP-DarkneSS** [comment]
We decided to add this patch and set KQOAUTH_LIBDIR via qmake execution.
https://build.opensuse.org/package/view_file?expand=1&file=libdir.patch&package=libkqoauth&project=openSUSE%3AFactory

**Comment by kypeli** [comment]
Thanks for sharing, looks like a good solution for you.
