### ISSUE TITLE
src/src.pro:78 incorrect for some 64-bit distros

### ISSUE THREAD

**Issue by eternaleye** [kypeli/kQOAuth#8]
Some 64-bit distros use lib64 as their libdir; changing line 78 in src/src.pro to

```
target.path = $$[QT_INSTALL_LIBS]
```

will resolve the issue.

**Comment by kypeli** [comment]
This was changed just some time ago to support Ubuntu packaging. In this merge request: https://github.com/smartboyhw/kQOAuth/commit/ad0519146c9d087dc5696c68c7396d4d12276ee0

I am no packaging expert, and I think the solution above is portable, but would there be any issues wrt. packaging with this change?

**Comment by eternaleye** [comment]
$$[QT_INSTALL_LIBS] should make it obey qmake's understanding of libdirs, which distros can generally handle - I actually submitted this because my distro (exherbo) has 'lib' as a symlink to 'lib64', and the package manager refuses to merge a directory over a symlink - thus, hardcoding 'lib' results in the package manager refusing to install the package.

However, setting QMAKESPEC appropriately (linux-g++-64 vs linux-g++) is pretty trivial, and is likely what most distros expect to Just Work - exherbo does it for every qmake-based package.

**Comment by kypeli** [comment]
I too had my concerns making this change to what Ubuntu expects. So I think making this change as suggested by you makes sense. Any distro that uses Qt should know how to handle this anyway.

**Comment by kypeli** [comment]
Solved in this commit:
https://github.com/kypeli/kQOAuth/commit/36c14beeb3fa09b899c43ecc288ea6d3e4fc5dee
